dataset = 'GTTTCGGAGCGTCGCTGCCGGCACCACGTGGTATTTGACGTTGGTACCGTAATTCGTATTGGTAGAGCGGGAAAGTAAGGTTCCATTAATTACGTACACGTTGATTCGCACTATTATAGCTACATTATCACAATAATATTGAACCAAGACAATCGGCTGACCTCTAGTAGACGGCGAACGGCGATGCTTCCAACCAATCTGACGCATTCGATGCAGGATAAGGTGAACATATCCACATCAGAATCGTCGCAAATTAACGTTCGAACAAGCACGGGATTCAGAATTGTGGATGAACGTGCCATACGACCGGCTAGACGTTCTACAGTACCTTGGGAGCAAATTGCGCTCTCAGCCTACTGGTTAGATGGTTGGGCGGCCGGCGCCGCTGACGGCCGCGAGAACCGCGTGAGACTCTTAGTCGCAAGGCTGTCTAATCACGCTCTGGGCCCACGCGCGACCAAGGACCTTTCATTGATCGGGCCTTATGATAACTATTTGTAGCGACACACGCGAGACCCCCTGGCCCACAATCGACGTACCGTTCAACGTTTGCAAAATACACGGAACGCAGTCGCTTGGCCCGACGGACTCTTACAAAATTATTGCCCTGGCAATGTTTCCACTGCTACCGACATCGACATCTGTTATCGATGAACTTGAGCAAGTCAGATTCGAGGGATTAAGTAAGTCAGATTAGGTCACTGGGCGGTTTTGTTGTCTTCTAGATCTAATGCATCGGGACATATCCAGAGGAGTCCAATAATCAGGTGGATCGTACTGTATCCAGCAAGGTCCTAATGGTCTCCTACAACGGACTTAATTCAGCTGTCAGCTTGGAGCGATGAAAGGTCGCCTATAACACACTAGGAATCAGTAACGGTGCCGCATCACATTACCGCTAGTCGGTGTGCGAGCCGATCCACTGTGGGTGGCTTCTCCGGAAGGGCCTCGCGTGTGCGGGCAACCTCCTTTTCTTACCAGTACACGACTACC'
result = ''

for nt in dataset:
    if nt == 'A':
        result = 'T' + result
    elif nt == 'T':
        result = 'A' + result
    elif nt == 'C':
        result = 'G' + result
    elif nt == 'G':
        result = 'C' + result

print(result)
