dataset = 'GTCTCGAGTGTGCACAATACCATTCGCACAAGAACCACCCTCAGGACCCAATTCGTCGACATGGTAGACCTGAGGGTCTCTAGTTCGTCCTCTAGTTGTTCGTCGAAAGACAACTACCGGCCTCTGCTCCCCTAGCCTTATGGACGGACGTTTTTCGTGACGGAAGGAGGATCCCTGTGAGCAGGACCCGGTCAGCATAAGATTTGTAGATCTCGCCGGGTGAGCTCATGACATCGTCTTTATTGCTCGGACTTCTGGCTTCTTATCGCGATCGGATCTATGTGAATTATTTACAATTCCTGTGGATACCACACGGTTGCGTGTCGGTCCAAGGATGAGGGCTTATCACCAAATTCTTTCCTTGCCCGGTCCAGTTCGACCGGCCGGACGAAAGTCGCGATGGCTCATAGCGTCCATCACCCGCAACAAGGCGATATCGTCAGTGATGCTCGAGACGCCCGTAGCGTATCGGCCCTACGAGCCATCGCTCCCAGACACTTGGCGAGGGGGGAACGACCTATGTTAGCTATTTCATCCCATGGGTCAGAGGTTGACTGCAGCTAGATGCCCGATTTTGCCCCGAGCGCTCGTGTCTATACTCCGAATCGTTCACTATGCATGCGTTTGCACAAACTACGAACAGTGCGACATTCTTCGGACTATCAAACGGACAATCCCCCGTATTCCAAGTAACGATAAAACAGCGTATGGGCAACTCCCGACTGGCTATCTTAATCTTCCAACGGTGCATGCCGCTAAAGATTACACGTTGATTACAGGTCTCCCTAGGGAGGCGCTCGGAT'

A = 0
C = 0
G = 0
T = 0

for n in dataset:
    if n == 'A':
        A += 1
    elif n == 'C':
        C += 1
    elif n == 'G':
        G += 1
    elif n == 'T':
        T += 1

print(str(A) + ' ' + str(C) + ' ' + str(G) + ' ' + str(T))
